//WebsitesOrbcommLocations.http
@WebsitesOrbcommLocations_HostAddress = http://localhost:5234

GET {{WebsitesOrbcommLocations_HostAddress}}/api/devices
Accept: application/json

###

GET {{WebsitesOrbcommLocations_HostAddress}}/api/health/database
Accept: application/json

###
